# Generated by Django 4.1.13 on 2024-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.IntegerField()),
                ('year2', models.IntegerField()),
                ('year3', models.IntegerField()),
                ('number_of_freshers1', models.IntegerField()),
                ('number_of_freshers2', models.IntegerField()),
                ('number_of_freshers3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Microsoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('recent1', models.TextField()),
                ('recent2', models.TextField()),
                ('recent3', models.TextField()),
                ('recent4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
